version: "3.9"

services:
  db:
    image: postgres:18
    container_name: PumpPatrol-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PumpPatrolDB
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
